#!/usr/bin/env node

module.exports = {
  addTodo: addTodo,
  getAll: getAll
}

var config = require('./knexfile').development
var db = require('knex')(config)

var cmd = process.argv[2]
var note = process.argv[3]

switch (cmd) {
  case 'add':
    addTodo(note, db)
      .then(function () { return getAll(db) })
      .then(listTodos)
      .catch(logError)
      .finally(closeDB)
    break

  case 'list':
    getAll(db)
      .then(listTodos)
      .catch(logError)
      .finally(closeDB)
    break

  default:
    console.log('No matched cases')
    closeDB()
    break
}

function listTodos (todos) {
  todos.forEach(function (todo) {
    console.info(todo.task)
  })
}

function logError (err) {
  console.error('Uh oh!', err)
}

function getAll (connection) {
  return connection('todos').select()
}

function addTodo (task, connection) {
  return connection('todos')
    .insert({
      task: task
    })
}

function closeDB () {
  db.destroy()
}

